/****** Object:  Table [dbo].[CATEGORIES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CATEGORIES](
	[Category_Name] [varchar](20) NOT NULL,
	[Parent_Category] [varchar](20) NULL,
 CONSTRAINT [PK_CATEGORIES] PRIMARY KEY CLUSTERED 
(
	[Category_Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CATEGORIES]  WITH CHECK ADD  CONSTRAINT [FK_ParentCategory] FOREIGN KEY([Parent_Category])
REFERENCES [dbo].[CATEGORIES] ([Category_Name])
ALTER TABLE [dbo].[CATEGORIES] CHECK CONSTRAINT [FK_ParentCategory]
