/****** Object:  Table [dbo].[CONTENTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CONTENTS](
	[Product] [int] NOT NULL,
	[Order] [bigint] NOT NULL,
	[Quantity] [tinyint] NULL,
 CONSTRAINT [PK_CONTENTS] PRIMARY KEY CLUSTERED 
(
	[Product] ASC,
	[Order] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CONTENTS]  WITH CHECK ADD  CONSTRAINT [FK_OrderContents] FOREIGN KEY([Order])
REFERENCES [dbo].[ORDERS] ([Order_ID])
ALTER TABLE [dbo].[CONTENTS] CHECK CONSTRAINT [FK_OrderContents]
ALTER TABLE [dbo].[CONTENTS]  WITH CHECK ADD  CONSTRAINT [FK_ProductContent] FOREIGN KEY([Product])
REFERENCES [dbo].[PRODUCTS] ([Product_ID])
ALTER TABLE [dbo].[CONTENTS] CHECK CONSTRAINT [FK_ProductContent]
