/****** Object:  Table [dbo].[CUSTOMERS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CUSTOMERS](
	[Customer_ID] [int] NOT NULL,
	[Email] [varchar](40) NOT NULL,
	[First_name] [varchar](20) NULL,
	[Last_name] [varchar](20) NULL,
	[Gender] [char](1) NULL,
	[Birth_Date] [date] NULL,
	[Join_Date] [date] NULL,
 CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED 
(
	[Customer_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CUSTOMERS]  WITH CHECK ADD  CONSTRAINT [CK_Email] CHECK  (([Email] like '%@%.%'))
ALTER TABLE [dbo].[CUSTOMERS] CHECK CONSTRAINT [CK_Email]
ALTER TABLE [dbo].[CUSTOMERS]  WITH CHECK ADD  CONSTRAINT [CK_Gender] CHECK  (([Gender]='F' OR [Gender]='M'))
ALTER TABLE [dbo].[CUSTOMERS] CHECK CONSTRAINT [CK_Gender]
