/****** Object:  Table [dbo].[CUSTOMER_BILLING]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CUSTOMER_BILLING](
	[Customer_ID] [int] NOT NULL,
	[Credit_Card] [varchar](20) NOT NULL,
 CONSTRAINT [PK_CUSTOMER_BILLING] PRIMARY KEY CLUSTERED 
(
	[Customer_ID] ASC,
	[Credit_Card] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CUSTOMER_BILLING]  WITH CHECK ADD  CONSTRAINT [FK_BillingCustomersBillings] FOREIGN KEY([Credit_Card])
REFERENCES [dbo].[BILLINGS] ([CC_Number])
ALTER TABLE [dbo].[CUSTOMER_BILLING] CHECK CONSTRAINT [FK_BillingCustomersBillings]
ALTER TABLE [dbo].[CUSTOMER_BILLING]  WITH CHECK ADD  CONSTRAINT [FK_CustomerCustomersBillings] FOREIGN KEY([Customer_ID])
REFERENCES [dbo].[CUSTOMERS] ([Customer_ID])
ALTER TABLE [dbo].[CUSTOMER_BILLING] CHECK CONSTRAINT [FK_CustomerCustomersBillings]
