/****** Object:  Table [dbo].[INTERESTS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[INTERESTS](
	[Customer_ID] [int] NOT NULL,
	[Interest] [varchar](15) NOT NULL,
 CONSTRAINT [PK_INTERESTS] PRIMARY KEY CLUSTERED 
(
	[Customer_ID] ASC,
	[Interest] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[INTERESTS]  WITH CHECK ADD  CONSTRAINT [FK_CustomerInterest] FOREIGN KEY([Customer_ID])
REFERENCES [dbo].[CUSTOMERS] ([Customer_ID])
ALTER TABLE [dbo].[INTERESTS] CHECK CONSTRAINT [FK_CustomerInterest]
