/****** Object:  Table [dbo].[PROJECT_PHOTO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PROJECT_PHOTO](
	[Customer] [int] NOT NULL,
	[Project_DT] [datetime] NOT NULL,
	[Photo_URL] [varchar](80) NOT NULL,
 CONSTRAINT [PK_PROJECT_PHOTO] PRIMARY KEY CLUSTERED 
(
	[Customer] ASC,
	[Project_DT] ASC,
	[Photo_URL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PROJECT_PHOTO]  WITH CHECK ADD  CONSTRAINT [FK_PhotoProjectsPhotos] FOREIGN KEY([Photo_URL])
REFERENCES [dbo].[PHOTOS] ([URL])
ALTER TABLE [dbo].[PROJECT_PHOTO] CHECK CONSTRAINT [FK_PhotoProjectsPhotos]
ALTER TABLE [dbo].[PROJECT_PHOTO]  WITH CHECK ADD  CONSTRAINT [FK_ProjectProjectsPhotos] FOREIGN KEY([Customer], [Project_DT])
REFERENCES [dbo].[PROJECTS] ([Customer_ID], [DT_Updated])
ALTER TABLE [dbo].[PROJECT_PHOTO] CHECK CONSTRAINT [FK_ProjectProjectsPhotos]
